contentType: Card
title: Approvals
name: my-approvals
CollectionModeField:
  CollectionMode: 0
MaxItemsField:
  MaxItems: 3
PriorityField:
  Priority: 5
StreamSource: null
CardComponent: my-approvals/my-approvals-card
StoreMetadataField:
  description: See your pending approvals, quick approve them or open the Approvals App to manage them.
  logourl: my-approvals/Approvals.svg
  storehide: !!bool false
  disableWorkplace: !!bool false
  promotion: !!bool true
CommonPart:
  Owner: !!int 2
  Container: null
  CreatedUtc: 2019-06-17T08:53:34.5568295Z
  PublishedUtc: 2019-06-17T12:48:34.9985117Z
  ModifiedUtc: 2019-06-17T12:48:34.9385153Z
  VersionCreatedUtc: 2019-06-17T12:48:34.0000000
  VersionPublishedUtc: 2019-06-17T12:48:34.0000000
  VersionModifiedUtc: 2019-06-17T12:48:34.0000000
ServicePart:
  ConnectorTypeId: !!int 0
  ConnectorName: Script
  ServiceName: Script
  Url: ~/api/adenin.GateKeeper.Script
  ServiceParameters: '{"tokens":""}'
SearchContextPart:
  Query: null
  Interface: null
CommandPart:
  CommandType: None
  Command: 
  DefaultDate: null
  Intent: null
  Ext: {}
AppPart:
  App: null
  Url: 
  ExtUrl: 
  Priority: !!int 0
  AppFaceId: !!int 0
  Category: orange
  Icon: now:search
  CSSClasses: null
  Enabled: !!bool false
  NewWindow: !!bool false
  UrlWithId: !!bool true
  AvailableAppFaceRecords: null
  HasPattern: !!bool false
RoleViewPermissionsPart:
  AllowedRoles: []
  Audiences:
    - Authenticated
  Mandatory: False
RecurringTaskPart:
  Schedule: '- - - - -'
  ActivityType: adenin.Now.Activities.CardTask.UpdateCard
  StartDateUtc: null
  EndDateUtc: null
  NextOccurrenceUtc: null
  Priority: !!int 5
  Status: Enabled
  NowFlag: 0
  LastExecutionUTC: null
  EnableWebHook: !!bool false
  WebHookToken: null
